version: "3.8"

services:
  database:
    image: mariadb
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}

  backend:
    image: xedom/codeduel-be
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    environment:
      AUTH_GITHUB_CLIENT_CALLBACK_URL: ${AUTH_GITHUB_CLIENT_CALLBACK_URL}
      AUTH_GITHUB_CLIENT_ID: ${AUTH_GITHUB_CLIENT_ID}
      AUTH_GITHUB_CLIENT_SECRET: ${AUTH_GITHUB_CLIENT_SECRET}
      BINARY_NAME: ${BINARY_NAME}
      FRONTEND_URL: ${FRONTEND_URL}
      FRONTEND_URL_AUTH_CALLBACK: ${FRONTEND_URL_AUTH_CALLBACK}
      HOST: ${HOST}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_PORT: ${MARIADB_PORT}
      MARIADB_USER: ${MARIADB_USER}
      PORT: ${PORT}
    depends_on:
      - database
  
  frontend:
    # image: xedom/codeduel-fe
    container_name: frontend
    profiles: ["prod"]
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      BACKEND_URL: http://backend:5000
    depends_on:
      - backend
