version: "3.8"

services:
  database:
    image: mariadb
    container_name: database
    restart: always
    ports:
      - 3306:3306
    environment:
      MARIADB_ROOT_PASSWORD: toor
      # MARIADB_RANDOM_ROOT_PASSWORD: 1
      # MARIADB_USER: $MARIADB_USER
      # MARIADB_PASSWORD: $MARIADB_PASSWORD
      # MARIADB_DATABASE: $MARIADB_DATABASE

